class CascadeGenerator:
    def set_graph(self, adj_list: list[list[int]]) -> None: ...
    def set_probabilities(self, probs: list[list[float]]) -> None: ...
    def set_delays(self, delays: list[float]) -> None: ...
    def set_symptom_probabilities(self, symptom_rates: list[float]) -> None: ...
    def generate_cascades(self, seeds: list[int], num_samples: int) -> list[list[tuple[int, float, bool]]]: ...
    def generate_cascade(self, seeds: list[int]) -> list[tuple[int, float, bool]]: ...


def hello_from_bin() -> str: ...